name: Cachix

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v15
      - name: Cachix
        # You may pin to the exact commit or the version.
        # uses: cachix/cachix-action@73e75d1a0cd4330597a571e8f9dedb41faa2fc4e
        uses: cachix/cachix-action@v10
        with:
          # Name of a cachix cache to push and pull/substitute
          name: chvp
          # Authentication token for Cachix, needed only for private cache access
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          pushFilter: "(-source$|-data-)"
      - run: nix build .#zeroad
      - run: nix-build | cachix push chvp
